apiVersion: apps/v1
kind: Deployment
metadata:
     name: myrc
spec:
    replicas: 3
    selector:
      matchLabels:
         env: ser
    template:
         metadata:
            labels:
              env: ser
         spec:
            containers:
                - name: nginxwala
                  image: nginx
                  ports:
                     - containerPort: 80
