apiVersion: v1
kind: ReplicationController
metadata:
     name: myrc
spec:
    replicas: 3
    selector:
        env: dev
    template:
         metadata:
            labels:
              env: dev
         spec:
            containers:
                - name: nginxwala
                  image: nginx
                  ports:
                     - containerPort: 80
